version: "3"

services:
  web:
    image: ic-moves-web
    build: ../IC-Moves
    ports:
      - "3000:3000"
    networks:
      - ic-moves

  api:
    image: ic-moves-api
    build: ../IC-Moves-API
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
    - ic-moves

  db:
    image: ic-moves-db
    build: .
    ports:
      - "3306:3306"
    networks:
      - ic-moves
    volumes:
      - data_volume:/var/lib/mysql

networks:
  ic-moves:
    driver: bridge

volumes:
  data_volume: